#' @title UpdateCells
#'
#' @description Update water and solute values in each cell.
#'
#' @param cells A list of cells in the model.
#' @param storesList A list of stores values generated by \code{CalcStores$new()}.
#'
#' @return A list of cells with updated water and solute values.
#'

UpdateCells <-
  R6::R6Class(
    classname = "UpdateCells",
    public =
      list(
        storesList = NULL,
        cells = NULL,
        initialize =
          function(cells, storesList){

            for(cellIdx in row.names(storesList[["H2O"]]) ){
              cellToUpdate <- cells[[which(sapply(cells, function(c) c$cellIdx) == cellIdx)]]

              cellToUpdate$channelVolume_L <- storesList[["H2O"]][cellIdx,"endVal"]
              cellToUpdate$channelVolume_m3 <- cellToUpdate$channelVolume_L / 1000
              cellToUpdate$channelDepth <- cellToUpdate$channelVolume_m3 / cellToUpdate$channelArea # assumes channel is a rectangular cuboid with fixed W and L

              #### Need to figure out how we want to calculate discharge so that
              #### we can update mean water velocity, channel residence time,
              #### and hydraulic load ###

              cellToUpdate$soluteMass <- storesList[["NO3"]][cellIdx, "endVal"]
              cellToUpdate$soluteConcentration <- cellToUpdate$soluteMass / cellToUpdate$channelVolume_L
            }
            return()
          }
      )

  )
